#!name=美团与美团外卖·试用
#!desc=20条已启用重写；2026-09-20整理，未验证当前App去广告效果。
# 原规则作者：zirawell/R-Store、fmz200/wool_scripts；合并及调整说明见随包README.md。
# GPL-3.0；许可证：https://raw.githubusercontent.com/zirawell/R-Store/1a92dd1a08db4841fe6ce85fd7e63bcf1bd21c5b/LICENSE
# 本文件不含被注释的可选规则；以下hostname与20条URL规则均启用。

hostname = img.meituan.net, p*.meituan.net, www.meituan.com, s3plus.meituan.net, flowplus.meituan.net, w.meituan.net, wmapi.meituan.com, sqt.meituan.com
^https?:\/\/img\.meituan\.net\/(adunion|display|midas)\/.+\.(gif|jpg)\.webp$ url reject-img
^https?:\/\/img\.meituan\.net\/groceryimages\/\w+\.gif url reject-img
^https?:\/\/img\.meituan\.net\/groceryimages\/\w+\.png@220w_220h_1e_1l url reject-img
^https?:\/\/p\d\.meituan\.net\/movie\/.+?\.jpg\?may_covertWebp url reject-img
^https?:\/\/p\d\.meituan\.net\/travelcube\/(?!1d4a663|52e9bfc|29a6227|412c4ac|6ee35c4|13bf0bf|ab8692e|6858b1d).+@100w_100h url reject-img
^https?:\/\/p\d\.meituan\.net\/linglong\/ url script-response-body https://raw.githubusercontent.com/zirawell/R-Store/1a92dd1a08db4841fe6ce85fd7e63bcf1bd21c5b/Res/Scripts/AntiAd/meituan.js
^https?:\/\/p\d\.meituan\.net\/(\d+\.\d+\.\d+\/)?wmbanner\/(?!fb51b9d|4e9d3c4).+\.gif url reject-img
^https?:\/\/p\d\.meituan\.net\/(display|mmc)\/ url reject
^https?:\/\/www\.meituan\.com\/api\/v\d\/appstatus\? url reject
^https?:\/\/(s3plus|flowplus)\.meituan\.net\/v\d\/\w+\/linglong\/.+\.(?>gif|jpg|mp4) url reject-img
^https?:\/\/s3plus\.meituan\.net\/v\d\/mss_\w+\/(brandcpt-vedio|waimai-alita)\/\w+\.zip$ url reject-dict
^https?:\/\/s3plus\.meituan\.net\/v\d\/mss_\w+\/brandcpt(?!-vedio\/\w+\.zip$) url reject
^https?:\/\/w\.meituan\.net\/v\d\/mss_\w+\/waimai-mach\/\d+\/\d+\/pt-im-(?>guider|coupon-card-stateful) url reject
^https?:\/\/sqt\.meituan\.com\/s\/gateway\/mweb\/api\/marketingResource\/show url reject
^https?:\/\/wmapi\.meituan\.com\/api\/v\d+\/(?>loadInfo|openscreen|startpicture)(?:\?|$) url reject-dict
^https?:\/\/p\d\.meituan\.net\/cell url reject
^https?:\/\/s3plus\.meituan\.net\/v\d\/mss_\w+\/goku\/(?>lottie|lucency) url reject-img
^https?:\/\/img\.meituan\.net\/bizad\/bizad_brandCpt_\d+\.jpg url reject-img
^https?:\/\/img\.meituan\.net\/goodsawardpic\/[a-f0-9]+\.png\.webp url reject-img
^https?:\/\/s3plus\.meituan\.net\/ocean-blk-index\/index\/blk_conf_73\.json url reject-dict
